export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


export const HEADER_TITLE = "HEADER_TITLE"
export const HEADER_DATE = "HEADER_DATE"
export const HEADER_IMAGE_URL = "HEADER_IMAGE_URL"
export const HEADER_DELETE_IMAGE_URL = "HEADER_DELETE_IMAGE_URL"

export const ANNOUNCEMENT_TITLE = "ANNOUNCEMENT_TITLE";
export const ANNOUNCEMENT_BODY_TEXT = "ANNOUNCEMENT_BODY_TEXT";
export const ANNOUNCEMENT_BUTTON_TEXT = "ANNOUNCEMENT_BUTTON_TEXT";
export const ANNOUNCEMENT_BUTTON_LINK = "ANNOUNCEMENT_BUTTON_LINK";
export const ANNOUNCEMENT_IMAGE_URL = "ANNOUNCEMENT_IMAGE_URL";
export const ANNOUNCEMENT_DELETE_IMAGE_URL = "ANNOUNCEMENT_DELETE_IMAGE_URL";

export const CONNECTCARD_TITLE = "CONNECTCARD_TITLE";
export const CONNECTCARD_IMAGE = "CONNECTCARD_IMAGE";
export const CONNECTCARD_BODY_TEXT = "CONNECTCARD_BODY_TEXT";
export const CONNECTCARD_QUESTION_ONE = "CONNECTCARD_QUESTION_ONE";
export const CONNECTCARD_QUESTION_ONE_OPTION_ONE = "CONNECTCARD_QUESTION_ONE_OPTION_ONE";
export const CONNECTCARD_QUESTION_ONE_OPTION_TWO = "CONNECTCARD_QUESTION_ONE_OPTION_TWO";
export const CONNECTCARD_QUESTION_TWO = "CONNECTCARD_QUESTION_TWO";
export const CONNECTCARD_QUESTION_TWO_OPTION_ONE = "CONNECTCARD_QUESTION_TWO_OPTION_ONE";
export const CONNECTCARD_QUESTION_TWO_OPTION_TWO = "CONNECTCARD_QUESTION_TWO_OPTION_TWO";
export const CONNECTCARD_CHECKED_VALUES = "CONNECTCARD_CHECKED_VALUES";

export const ORDEROFSERVICE_TITLE = "ORDEROFSERVICE_TITLE";
export const ORDEROFSERVICE_TOPIC_TITLE = "ORDEROFSERVICE_TOPIC_TITLE";
export const ORDEROFSERVICE_TOPIC_CONTENT = "ORDEROFSERVICE_TOPIC_CONTENT";
export const ORDEROFSERVICE_IMAGE_URL = "ORDEROFSERVICE_IMAGE_URL";
export const ORDEROFSERVICE_DELETE_IMAGE_URL = "ORDEROFSERVICE_DELETE_IMAGE_URL";

export const EVENT_TITLE = "EVENT_TITLE";
export const EVENT_IMAGE = "EVENT_IMAGE";
export const EVENT_BODY_TEXT = "EVENT_BODY_TEXT";
export const EVENT_DATE = "EVENT_DATE";
export const EVENT_TIME_START = "EVENT_TIME_START";
export const EVENT_TIME_END = "EVENT_TIME_END";
export const EVENT_LOCATION = "EVENT_LOCATION";
export const EVENT_BTN_TEXT = "EVETNT_BTN_TEXT";
export const EVENT_BTN_LINK = "EVNET_BTN_LINK";
export const EVENT_IMAGE_URL = "EVENT_IMAGE_URL";
export const EVENT_DELETE_IMAGE_URL = "EVENT_DELETE_IMAGE_URL";

export const PRAYER_TITLE = "PRAYER_TITLE";
export const PRAYER_BODY_TEXT = "PRAYER_BODY_TEXT";
export const PRAYER_CHECKED_VALUE = "PRAYER_CHECKED_VALUE";

export const ONLINE_TITLE = "ONLINE_TITLE";
export const ONLINE_BODY_TEXT = "ONLINE_BODY_TEXT";
export const ONLINE_TYPE = "ONLINE_TYPE";
export const ONLINE_LINK = "ONLINE_LINK";

export const WEBSITE_TITLE = "WEBSITE_TITLE";
export const WEBSITE_TYPE = "WEBSITE_TYPE";
export const WEBSITE_LINK = "WEBSITE_LINK";
export const WEBSITE_EMBED_CODE = "WEBSITE_EMBED_CODE";

export const VIDEO_TITLE = "VIDEO_TITLE";
export const VIDEO_BODY_TEXT = "VIDEO_BODY_TEXT";
export const VIDEO_PLATFORM = "VIDEO_PLATFORM";
export const VIDEO_LINK = "VIDEO_LINK";