export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_BULLETIN = "GET_BULLETIN";
export const CLEAN_ERROR = "CLEAN_ERROR";
export const CLEAR_REDUX_STORE = "CLEAR_REDUX_STORE";
export const RETRIEVE_DATA = "RETRIEVE_DATA";
export const SAVE_BULLETIN_SUCCESS = "SAVE_BULLETIN_SUCCESS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";
export const SEND_SMS = "SEND_SMS";
export const MOBILE_REGISTER = "MOBILE_REGISTER";
export const SET_DATA_SOURCE = "SET_DATA_SOURCE";
export const FETCH_USER_ALL = "FETCH_USER_ALL";
export const ICON_UPLOAD = "ICON_UPLOAD";
export const DELETE_ICON_URL = "DELETE_ICON_URL";


export const HEADER_TITLE = "HEADER_TITLE"
export const HEADER_DATE = "HEADER_DATE"
export const HEADER_IMAGE_URL = "HEADER_IMAGE_URL"
export const HEADER_DELETE_IMAGE_URL = "HEADER_DELETE_IMAGE_URL"



export const SET_TODO_LIST = "SET_TODO_LIST";
export const SET_DETAILED_TODO_LIST = "SET_DETAILED_TODO_LIST";
export const SET_SECTION_IMAGE_UPLOAD = "SET_SECTION_IMAGE_UPLOAD";
export const SET_SMALL_SECTION_DATA = "SET_SMALL_SECTION_DATA";
export const DELETE_IMAGE_URL = "DELETE_IMAGE_URL";
export const SET_CURRENT_TODOLIST = "SET_CURRENT_TODOLIST";
export const SET_DELTE_AFTER_TODOLIST = "SET_DELTE_AFTER_TODOLIST";

export const SET_HEADTEXT_COLOR = "SET_HEADTEXT_COLOR";
export const SET_BACKGROUND_COLOR = "SET_BACKGROUND_COLOR";
export const SET_SECTION_BACKGROUND_COLOR = "SET_SECTION_BACKGROUND_COLOR";
export const SET_SECTION_TITLE_COLOR = "SET_SECTION_TITLE_COLOR";

